### ISSUE TITLE
Make a new action to getPursuanceById

### ISSUE THREAD

**Issue by v-stickykeys** [PursuanceProject/ensue#136]
From the problem I ran into yesterday at NoiseBridge..

currently we are keeping currentPursuanceId in state, but if we want any other information about the pursuance with that id, we also have to subscribe to all pursuances. I think it would be better if we create an action called getPursuanceById that would retrieve the json for a particular pursuance, so we don't have to track all 1000+ pursuances when we render each component.

**Comment by elimisteve** [comment]
@thevaleriemack You mean like this? :-) https://github.com/PursuanceProject/pursuance/blob/914a360debb90ad81d78943484642202b83d001f/src/actions/index.js#L30

**Comment by elimisteve** [comment]
@thevaleriemack Soon we won't fetch all pursuances and put them in Redux, we'll just fetch the ones that a user is a member of, or just the one that a user is looking at (in the case where the directly visit a page like `/pursuances/1/discuss/task/1_38`).  So I think we still should subscribe to the `pursuances` key in Redux (especially since pursuance objects don't change that often), but I agree that being able to fetch just 1 Pursuance from the backend is useful and more efficient than always fetching all of them :+1: .

**Comment by elimisteve** [comment]
Finished in https://github.com/PursuanceProject/pursuance/blob/914a360debb90ad81d78943484642202b83d001f/src/actions/index.js#L30-L33

**Comment by v-stickykeys** [comment]
I see! So since we are fetching all pursuances that the user will have access to upon login, it is better to use that list to get info about a particular pursuance than to hit the db again?

I guess what I'm trying to understand is if there is any performance optimization. But it seems that if one component is subscribing to all accessible pursuances, than its best to just have other components subscribe to them too.

**Comment by elimisteve** [comment]
> So since we are fetching all pursuances that the user will have access to upon login, it is better to use that list to get info about a particular pursuance than to hit the db again?

Just replace "will have access to" with "will be a member of", and yes :+1: .

Also, once we fetch all pursuances that a user is a member of, those won't change very frequently at all, and thus won't trigger re-renders hardly at all.

Plus, I see that you've smartly created `publicPursuances` and put all the downloaded public pursuances into there, which is separate from Redux's `pursuances`, which stores the pursuances that a user is a member of.

I think I now understand the broader context of the optimization(s) you're looking to make, and "lazily" fetching public pursuances _as they are needed_, rather than fetching all public pursuances up front, I agree is probably a good idea.

I didn't realize you were talking about public pursuances :-) , and yes there will be many of those.

Thanks to PostgREST, we can easily paginate by doing a query like...

`/pursuances?limit=50&offset=0&encrypted=is.false&order=name.asc` to get page 1,

`/pursuances?limit=50&offset=50&encrypted=is.false&order=name.asc` to get page 2,

`/pursuances?limit=50&offset=100&encrypted=is.false&order=name.asc` to get page 3,

and so on, to get all public (unencrypted) pursuances in order by name (ascending).

...but we can do even better than that, I just realized, and add something like `&id=not.in.(1,2,4)` to these queries to just fetch the public pursuances _that we don't already have in redux!_

If you want to add this fanciness, that's cool with me :-D . It'll be a little while before we need to worry about fetching too many pursuances' data at once, so we can delay this and prioritize more immediate things if you'd prefer.  Up to you and what you're most interested in :-).
